#!/bin/bash


#Required Inputs 2 worker nodes
name_of_master=$(zenity --entry --title="Master node" --text="Enter name of Master node : ")
ip_master=$(zenity --entry --title="Master ip" --text="Enter the ip of master : ")
password_of_master=$(zenity --entry --title="Password of master" --text="Enter the password of master : ")

name_of_node1=$(zenity --entry --title="Worker node1" --text="Enter name of your node1 : ")
ip_node1=$(zenity --entry --title="ip of worker node1" --text="Enter ip of your node1 : ")
password_of_node1=$(zenity --entry --title="Password of worker node1" --text="Enter the password of node1 : ")

name_of_node2=$(zenity --entry --title="Worker node2" --text="Enter name of your node2 : ")
ip_node2=$(zenity --entry --title="ip of worker node2" --text="Enter ip of your node2 : ")
password_of_node2=$(zenity --entry --title="Password of worker node" --text="Enter the password of node2 : ")

#read -p "Enter name of Master node : " name_of_master
#read -p "Enter the ip of master : " ip_master
#read -p "Enter the password of master : " password_of_master

#read -p "Enter name of your node1 : " name_of_node1
#read -p "Enter ip of your node1 : " ip_node1
#read -p "Enter the password of node1 : " password_of_node1

#Disabling Firewall
systemctl stop firewalld.service; systemctl stop firewalld
systemctl disable firewalld.service; systemctl disable firewalld

#Disabling SELINUX
setenforce 0
sed -i 's/^SELINUX=.*/SELINUX=disabled/g' /etc/selinux/config

#Changing HOSTNAME
#hostnamectl set-hostname $name_of_master
#exec bash

#Adding entries in /etc/hosts
echo "$ip_master $name_of_master" >> /etc/hosts
echo "$ip_node1 $name_of_node1" >> /etc/hosts
echo "$ip_node2 $name_of_node2" >> /etc/hosts

#Passwordless SSH
#cat /etc/sysconfig/selinux
#read -p "Enter ip of node 1 : " node1_ip
#read -p "Enter ip of node 2 : " node2_ip
ssh-keygen
sshpass -p "$password_of_node1" ssh-copy-id "$name_of_node1@$ip_node1"
sshpass -p "$password_of_node2" ssh-copy-id "$name_of_node2@$ip_node2"
#ssh-copy-id root@$ip_node1

#ssh-keygen root@$node1_ip
#ssh-copy-id root@$node_ip
#echo "root@$node1_ip"

#Munge Installation
yum install epel-release -y
yum install munge munge-libs munge-devel

/usr/sbin/create-munge-key -r
scp /etc/munge/munge.key

systemctl start munge.service
systemctl enable munge.service

#Downloading extra stuff

yum install pam-devel -y
yum install python3 -y
yum install readline-devel -y
yum install perl-ExtUtils-MakeMaker -y
yum install mysql-devel -y
yum install gcc -y

#Downloading Slurm stuff

wget https://download.schedmd.com/slurm/slurm-20.11.9.tar.bz2
yum install rpm-build -y
rpmbuild -ta slurm-20.11.9.tar.bz2

export SLURMUSER=900
groupadd -g $SLURMUSER slurm
useradd -m -c "Medera" -d /var/lib/slurm -u $SLURMUSER -g slurm -s /bin/bash slurm
mkdir /home/rpms
cd /root/rpmbuild/RPMS/x86_64
cp * /home/rpms
yum --nogpgcheck localinstall * -y

#After installation of SLURM

mkdir /var/spool/slurm
chown slurm:slurm /var/spool/slurm/
chmod 755 /var/spool/slurm/
mkdir /var/log/slurm
chown -R slurm:slurm /var/log/slurm/

touch /var/log/slurm/slurmctld.log
chown slurm:slurm /var/log/slurm/slurmctld.log
touch /var/log/slurm_jobacct.log /var/log/slurm_jobcomp.log
chown slurm:slurm /var/log/slurm_jobacct.log
chown slurm:slurm /var/log/slurm_jobcomp.log
cp /etc/slurm/slurm.conf.example /etc/slurm/slurm.conf
