############## Only Master ##############################
---
- name: Configure SLURM Control Node
  hosts: localhost
  become: true
  tasks:

    - name: Download SLURM tarball
      get_url:
        url: https://download.schedmd.com/slurm/slurm-20.11.9.tar.bz2
        dest: /root/slurm-20.11.9.tar.bz2  # Specify the destination path

    - name: extract SLURM tar file
      command: rpmbuild -ta /root/slurm-20.11.9.tar.bz2

    - name: Create /home/rpms directory
      file:
        path: /home/rpms
        state: directory

    - name: Copy RPMs to /home/rpms
      synchronize:
        src: /root/rpmbuild/RPMS/x86_64/
        dest: /home/rpms/

    - name: List directory content
      find:
        paths: /home/rpms/
        patterns: "*.rpm"
      register: rpm_file_result


    - name: Install RPM file
      yum:
        name: "{{ rpm_file_result.files[0].path }}"
        state: present
      when: rpm_file_result.matched > 0


    - name: Generate MUNGE key
      command: /usr/sbin/create-munge-key > /etc/munge/munge.key
      changed_when: false

        - name: Copy slurm.conf.example to /etc/slurm/slurm.conf
      copy:
        src: /etc/slurm/slurm.conf.example
        dest: /etc/slurm/slurm.conf


    - name: Create slurmctld.log
      file:
        path: /var/log/slurm/slurmctld.log
        state: touch

    - name: Change ownership of slurmctld.log
      file:
        path: /var/log/slurm/slurmctld.log
        owner: slurm
        group: slurm

    - name: Create slurm_jobacct.log and slurm_jobcomp.log
      file:
       path: /var/log/slurm_jobacct.log
       state: touch

    - name: Change ownership of slurm_jobacct.log and slurm_jobcomp.log
      file:
        path: /var/log/slurm_jobacct.log
        owner: slurm
        group: slurm

    - name: Change ownership of slurm_jobcomp.log
      file:
        path: /var/log/slurm_jobcomp.log
        owner: slurm

    - name: Edit slurm.conf
      lineinfile:
        path: /etc/slurm/slurm.conf
        regexp: '^ControlMachine='
        line: 'ControlMachine=master'

