---
- name: Run slurmd -C command
  hosts: nodes
  become: true
  tasks:
    - name: Run command using command module
      command: slurmd -C
      register: node_output

    - name: Save ls command output to file
      copy:
        content: "{{ node_output.stdout }}"
        dest: /node_output.txt

    - name: Fetch file from remote host
      fetch:
        src: /node_output.txt
        dest: /tmp/node_output.txt
        flat: yes

